sudo: required
dist: trusty
language: node_js
node_js:
- 6
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0

script:
  - npm test

cache:
    bundler: true
    directories:
    - node_modules
    - .coala-cache

